### ISSUE TITLE
Start a how-to for common usage patterns

### ISSUE THREAD

**Issue by matthewmueller** [leebyron/async-to-gen#2]
Loving these standalone compiler modules :-D

Just created a tiny, tiny wrapper around this library for mocha: https://github.com/matthewmueller/async-mocha

May want to start something in the readme for including this compiler in some of the more common frameworks. 

Nice work! ✨

**Comment by leebyron** [comment]
Nice!

Maybe I should include something like for that case?

```bash
mocha --require async-to-gen/register test.js
```

Any other usage suggestions? Happy to add more as they come up

**Comment by matthewmueller** [comment]
Yep, that works fine too :-)

I'm a serial [co-mocha](https://github.com/blakeembrey/co-mocha) user, so not having to call register is one less thing to remember.

**Comment by leebyron** [comment]
I added an example of using mocha and interactive scripts as those are two I end up using async functions for all the time.

**Comment by matthewmueller** [comment]
looks good!
