### ISSUE TITLE
Use with Jest

### ISSUE THREAD

**Issue by Uhsac** [leebyron/async-to-gen#20]
Hello there,

Do someone know if it's possible to use async-to-gen with Jest ?

I can use it with ava or mocha with `async-to-gen/register` but Jest don't seem to have a feature like that. On their Async docs they say to use babel-jest (https://facebook.github.io/jest/docs/tutorial-async.html#content).

Thanks

**Comment by leebyron** [comment]
Added the bit of code Jest looks for, so it should work out of the box now.

**Comment by Uhsac** [comment]
Oh that was fast ! Thanks a lot !
