### ISSUE TITLE
TypeError: Cannot read property 'type' of null

### ISSUE THREAD

**Issue by albinekb** [leebyron/async-to-gen#22]
I got this error, don't know why yet (checking and will update when i know what caused it)

```
.../node_modules/async-to-gen/index.js:451
if (node && typeof node === 'object' && (node.type || node.length && node[0].type)) {
                                                                                  ^
TypeError: Cannot read property 'type' of null
```

Probably a good idea to check if `node[0].type` exists and throw if it doesn't 😬  with a possible cause (once i've found out what caused this) 💭

**Comment by albinekb** [comment]
Here's the problem:

I was using this syntax (which is valid):
```
const string = 'Albin Ekblom
const [, lastName] = string.split(' ')
``

**Comment by leebyron** [comment]
Yikes, thanks for the report!

**Comment by albinekb** [comment]
No probs 😄 

Am I the only one using this syntax hehe? 😂

**Comment by albinekb** [comment]
I'll try to get it fixed and add a test-case for it later tonight 🎉

**Comment by leebyron** [comment]
I've got one coming, I'll unblock you :)

**Comment by albinekb** [comment]
Amazing 🎉 
Thanks @leebyron

**Comment by leebyron** [comment]
New version available on npm now, hopefully that works for you!

**Comment by albinekb** [comment]
Confirmed, works 🎉  thanks for fast fix!
