### ISSUE TITLE
In node.js sourceMaps off?

### ISSUE THREAD

**Issue by darky** [leebyron/async-to-gen#23]
https://github.com/leebyron/async-to-gen/blob/master/register.js#L10

**Comment by leebyron** [comment]
Sorry I don't understand what you're asking for, you're going to have to elaborate with more than a link to the existing source code

**Comment by darky** [comment]
https://github.com/leebyron/async-to-gen/blob/master/index.js#L17
Here I see that `sourceMap` option `false` default
https://github.com/leebyron/async-to-gen/blob/master/register.js#L10
Here I see, that `sourceMap : true` option not passed

Theremore I conclude, that node.js runtime generated files don't have sourcemaps?

**Comment by leebyron** [comment]
That is correct. Node does not have support for source maps.

**Comment by darky** [comment]
Not exactly.
Coverage tools like https://github.com/istanbuljs/nyc can't show source code without sourcemaps.
Also debugging tools like https://github.com/Jam3/devtool don't show original source code.
Seems need to allow pass options to register like `require('async-to-gen/register')(options)`

**Comment by leebyron** [comment]
I would be happy to entertain pull requests for better istanbul and devtool support
