### ISSUE TITLE
require hook is only usable in development?

### ISSUE THREAD

**Issue by nfcampos** [leebyron/async-to-gen#27]
due to this line https://github.com/leebyron/async-to-gen/blob/master/register.js#L9 the require hook only works in development since if a package is installed from npm it will most likely contain `node_modules` in its path.
is this on purpose?
if so, then maybe a line should be added to the readme alerting people to this.

**Comment by leebyron** [comment]
This is on purpose as packages distributed on npm are intended to be used in node without any additional runtime. You should use async-to-gen to produce the compiled artifacts to distribute on npm. 

Require hooks are only for development use. They introduce an overhead typically deemed unacceptable for production use. You should typically only deploy compiled files

**Comment by leebyron** [comment]
Just added a note to the readme about this! Thanks for the recommendation

**Comment by nfcampos** [comment]
Thanks! I was trying to use it in production for a small CLI tool, which is why i wasn't worried that it would affect the whole runtime, seeing as it wasn't meant to ever be imported. but anyway it wasn't that much of a pain to set up a build step ;)

**Comment by raphaelokon** [comment]
Same here … that tripped me on the patternlab-node-cli. Just adding the build step ^^
