### ISSUE TITLE
`referencesArgs: true` causes SyntaxError in strict mode

### ISSUE THREAD

**Issue by oliverwoodings** [leebyron/async-to-gen#28]
Hi @leebyron, first of all thanks for such an awesome library! This + node6 = a dream.

I've got an issue where referencing `arguments` in an async function is causing `async-to-gen` to create an argument called `arguments`, which is disallowed in strict mode. It causes the following to happen:

![screen shot 2016-11-02 at 10 02 47](https://cloud.githubusercontent.com/assets/621323/19924523/33463c8c-a0e4-11e6-97fb-4df9afab8c2d.png)

Here is the original bit of code at that point:

![screen shot 2016-11-02 at 10 08 18](https://cloud.githubusercontent.com/assets/621323/19924548/4da1fa6c-a0e4-11e6-944f-630391c0b4da.png)

Is there some way to fix this? I was looking at the source and trying to understand why you need to explicitly pass `arguments` through - how come you can't use `apply` with the original args?

**Comment by leebyron** [comment]
Thanks for the report - I'll look into the best way to do this.

**Comment by oliverwoodings** [comment]
Thanks for the fix!

**Comment by leebyron** [comment]
Just released a new version with this fix included
