### ISSUE TITLE
async-to-gen compiles the tree

### ISSUE THREAD

**Issue by matthewmueller** [leebyron/async-to-gen#3]
I think async-to-gen would be quite a bit more useful if it was more like async-node, where if you do `async-to-gen index.js --out build` it'll walk the dependencies and write them out.

If that works for you, I think the easiest way would be to create a `require.extensions` function that writes out the transformed files.

**Comment by leebyron** [comment]
I'd rather not expand the scope of the module to deal with dependency resolution, especially since there are so many great ones already out there like webpack, browserify, and rollup

**Comment by leebyron** [comment]
Added to the readme, but something like https://github.com/leebyron/rollup-plugin-async will get the behavior you're looking for walking dependencies
