### ISSUE TITLE
Unexpected yield from async function with for await statement

### ISSUE THREAD

**Issue by alexeyraspopov** [leebyron/async-to-gen#30]
Here is code I have:

```javascript
class Dispatcher {
  async dispatch(message) {
    this.mailbox.enqueue(message);

    if (!this.isDispatching) {
      this.isDispatching = true;

      for await (const message of this.mailbox) {
        for (const task of this.tasks) task(message);
      }

      this.isDispatching = false;
    }
  }
}
```

After using `async-to-gen Dispatcher.js > D.js` I'm seeing this:

```javascript
class Dispatcher {
  dispatch(message) {return __async(function*(){
    this.mailbox.enqueue(message);

    if (!this.isDispatching) {
      this.isDispatching = true;

      for (let $await1 of this.mailbox) {const message=yield{__await:$await1};
        for (const task of this.queue) task(message);
      }

      this.isDispatching = false;
    }
  }.call(this))}
}
```

And there is a problem here: 

> `const message=yield{__await:$await1};`

A `message` becomes an object with the actual value inside which breaks consequent logic.

Is it a bug or something wrong with my code? It works with `babel-node` and `babel-preset-stage-3`.

**Comment by leebyron** [comment]
Hmm perhaps a bug. We use this wrapping object to differentiate from yield statements in "async function *" async generator functions. The wrapping helper function converts them back.

**Comment by alexeyraspopov** [comment]
This unwrapping logic [exists](https://github.com/leebyron/async-to-gen/blob/master/index.js#L106) in `__asyncGen` helper but [not](https://github.com/leebyron/async-to-gen/blob/master/index.js#L74) in `__async`. Can we just do the same thing? I can open a PR for this.

**Comment by alexeyraspopov** [comment]
I've scoped the bug to this code snippet:

```javascript
async function foo() {
  for await (const bar of baz) {
    console.log(bar);
  }
}
```

So, it's just about async function (not generator) with `for..await` statement.

**Comment by leebyron** [comment]
Thanks for narrowing it down. Ideally we do not need to alter the __async helper. This seems like a scope problem where the for await loop is causing the code generator to produce the incorrect output

**Comment by alexeyraspopov** [comment]
Right, the code generator can treat for await loop as 

```javascript
for (const $bar of baz) {
  const bar = await $bar;
}
```

Which produces the code with `__async` but with not wrapped values.

**Comment by alexeyraspopov** [comment]
But, doing this way `Symbol.iterator` is used, not `Symbol.asyncIterator`...

**Comment by leebyron** [comment]
Just released a new version with the fix

**Comment by alexeyraspopov** [comment]
That's amazing, thank you @leebyron!
