### ISSUE TITLE
Is there a way to remove the require hook?

### ISSUE THREAD

**Issue by shawninder** [leebyron/async-to-gen#31]
From the README:

```javascript
require('async-to-gen/register')
require('./some-module-with-async-functions')
```

What if only need the hook for one file? Is there a way to remove the hook after it's done being useful? Something like:

```javascript
var undo = require('async-to-gen/register')
require('./some-module-with-async-functions') // works
undo()
require('./another-module-with-async-functions') // breaks
```

**Comment by leebyron** [comment]
Interesting, there isn't currently a way to do this. Do other libraries with require hooks provide the same functionality? It would be great to see one to understand the nuances.

**Comment by shawninder** [comment]
The only one I know of is a little thing I made that allows you to instruct `require` to ignore style files and others and return the package.json on `require('package')` and stuff like that: https://github.com/vigour-io/enhance-require

Here's an example:

```javascript
const enhanceRequire = require('enhance-require')
enhanceRequire()
require('styles.less') // ignored in node, processed elsewhere
// Don't forget to add a browserify transform or similar for non-node
enhanceRequire.restore() // Restores the original behavior of `require`
require('style2.less') // This will now break because less code is not valid javascript
```

I haven't used this module in a while, not sure how well it works, but it does illustrate what I'm talking about here. Is that what you meant?

**Comment by leebyron** [comment]
Partially yes. The API is one thing, but I'm interested in use cases and implementation details. For example, does babel or typescript or something like that support this feature we could learn from?

**Comment by shawninder** [comment]
I understand. But I don't know. I expect this pattern of changing the behaviour of `require` isn't too common, actually. People are usually very wary of modifying the behaviour of "language-level features"...

For this particular module, the use case I'm imagining is the case where you have a single file out of many which needs this. In this case, you would want this module to treat only that file and not have it read all other files only to notice they don't have async functions in them (to speed things up).

As for implementation details, unfortunately, I don't know of any experiments that have been made with this type of thing..

**Comment by leebyron** [comment]
Perhaps a better fix is to add an "excludes" option to the require hook? I think other require hooks offer this kind of tool for the use case you're talking about.

Right now this library hard-codes such an excludes list to ignore the `node_modules` directory

**Comment by shawninder** [comment]
An `excludes` option is a good idea.

Perhaps an `includes` option could also be considered?

**Comment by leebyron** [comment]
Yep! I think that's a good idea. The default includes should be "all" and the default excludes should be "node_modules/" - then the check could be `if (isIncluded && !isExcluded)`

**Comment by hzoo** [comment]
Yep Babel has excludes with node_modules excluded as the default
