### ISSUE TITLE
Better output when parser fails

### ISSUE THREAD

**Issue by oliverwoodings** [leebyron/async-to-gen#32]
Right now if you have a syntax error, babylon fails but doesn't actually tell you where the issue is - the stack trace just points to babylon itself:

<img width="958" alt="screen shot 2016-11-20 at 19 35 40" src="https://cloud.githubusercontent.com/assets/621323/20465604/c62d9df6-af58-11e6-8c6f-5ee9f891aa3b.png">

Is there any way to get better output from this, or am I missing something?

**Comment by leebyron** [comment]
I think babylon might have improved their errors in a more recent version - I'll take a look

**Comment by leebyron** [comment]
Indeed, updating to latest babylon highlights the line with the issue which is much nicer. I just updated the dependencies to pull it in

**Comment by oliverwoodings** [comment]
You're on 🔥! Thanks again
