### ISSUE TITLE
Indlude a specific dir inside node_modules

### ISSUE THREAD

**Issue by cognitom** [leebyron/async-to-gen#41]
I have a small library written with `async-to-gen`. At this point, [I had to hack a bit](https://github.com/cognitom/paper-css/blob/master/bin/paper.js) like this:

```javascript
// works
require('async-to-gen/register')({
  excludes: /\/node_modules\/(?!my-library\/)/
})
```

On the other hand, `async-to-gen` ignores `node_modules` by default, so the code below doesn't work:

```javascript
// doesn't work
require('async-to-gen/register')
```

Is there any other good ways to use `async-to-gen` inside a library?

Or..., can we change [this line](https://github.com/leebyron/async-to-gen/blob/492d9605e74de1c83ba4362cb04d2c11b2b9dd94/register.js#L47) `if (isIncluded && !isExcluded)` to `if (isIncluded || !isExcluded)`? Then we could simply write like this, I think:

```javascript
// hope to work
require('async-to-gen/register')({
  includes: /\/node_modules\/my-module\//
})
```

Related to #31

BTW, I'm enjoying `async/await`. Thank you for your cool library 😄

**Comment by leebyron** [comment]
Hey, thanks for the report. Your specific `excludes` is what I would have suggested.

However I have to ask - why are you developing your library source in the node_modules folder? That should be preserved for npm distributed packages.

**Comment by leebyron** [comment]
We specifically should not change the && to || in testing includes and excludes. Changing to || could cause files that were requested to be excluded to be inadvertently included.

The "node_modules" default excludes can be overridden if you wish, you can also pass `excludes: null` along with `includes: ...` to focus only on a whitelist of files to include rather than exclude.

**Comment by leebyron** [comment]
Finally - remember to only use the require register hook during development!

More on that:
https://github.com/leebyron/async-to-gen#dont-use-the-require-hook-in-packages-distributed-on-npm

**Comment by cognitom** [comment]
@leebyron that totally makes sense. I'll precompile my codes.
Thank you so much for your clarification and detail!
