### ISSUE TITLE
Arrow function with parenthesised object literal causes syntax error

### ISSUE THREAD

**Issue by aslakhellesoy** [leebyron/async-to-gen#49]
First off - thanks for a brilliant library. I'm using it in conjunction with [FinishedPromise](https://github.com/featurist/finished-promise) and mocha to write tests that *cannot be slow* :-)

I've found a bug though. This code:

```javascript
async () => ({})
```

gets transpiled to this:

```javascript
() =>__async(function*(){ (return {a:1}}()))
```

which is not valid JavaScript. I believe it ought to be translated to this (but I'm not 100% sure)

```javascript
() =>__async(function*(){ return {a:1}}())
```

I tried various things in `leaveArrowFunction`, but couldn't come up with something that worked without breaking the tests yet. Would be great to have a fix for this!

**Comment by leebyron** [comment]
Thanks for reporting this bug and sorry for the huge wait. I've put up a PR to fix this and will get it released ASAP

**Comment by aslakhellesoy** [comment]
Thank you @leebyron!
