### ISSUE TITLE
[async-node]: support for require flag?

### ISSUE THREAD

**Issue by olstenlarck** [leebyron/async-to-gen#51]
So then we can just `async-node -x .mjs,.js,.jsx -r @std/esm foo.mjs`

**Comment by olstenlarck** [comment]
The case is that i'm thinking for such scenario:

1. When on node 8 then `node --experimental-modules test.mjs`
2. when on 6+ then `node --require @std/esm test.mjs`

That's okey, until you realized that node 6 dont have async/await, so here should come `async-to-gen`. It's register hooks seems to not work well with the `@std/esm`. Btw, i think it is a problem of `std/esm` cuz it not works in `nyc` too.

But, another way to do that is to you `async-node` and pass `std/esm` to it.

Btw, the register hook, may not work because don't accept `.mjs`? Definitely should be added to the defaults.

**Comment by olstenlarck** [comment]
It seems like it has the support for the `--require`, but cant load `@std/esm` properly..

```
SyntaxError: Unexpected token import
```

**Comment by leebyron** [comment]
I believe `@std/esm` attempts to transform sources live, so I would recommend first transforming your source files with `async-to-gen` to replace async/await statements, then used the output of that alongside `@std/esm`. Otherwise, the intermediate state of a half-transformed file will not behave as expected.

**Comment by jdalton** [comment]
@leebyron Have you seen [pirates](https://www.npmjs.com/package/pirates). It's what `@babel/register` uses to register its hooks. If you use that it would work seamlessly with things like `@std/esm` esp if you allowed the `-r` flagged code to run before your hook.

**Comment by olstenlarck** [comment]
Yup, closing.

**Comment by leebyron** [comment]
Thanks for the reference, @jdalton I'll check it out
